project:
  type: book

book:
  title: "NHP Community Mitigators"
  author: "Anya Ferguson and Sarah Lucas"
  date: last-modified
  date-format: "YYYY-MM-DD"
  chapters:
    - index.qmd
    - summary_of_total_mitigation.qmd
    - part: efficiencies.qmd
      chapters: 
        - raid_ip.qmd
        - emergency_elderly.qmd
        - stroke_early_supported_discharge.qmd
    - part: efficiencies_relocation.qmd
      chapters: 
        - virtual_wards_activity_avoidance_ari.qmd
        - virtual_wards_activity_avoidance_heart_fai.qmd
    - part: prevention.qmd
      chapters: 
        - alcohol_partially_attributable_acute.qmd
        - alcohol_partially_attributable_chronic.qmd
        - alcohol_wholly_attributable.qmd
        - intentional_self_harm.qmd
        - medically_unexplained_related_admissions.qmd
        - raid_ae.qmd
        - obesity_related_admissions.qmd
        - smoking.qmd
    - part: mechanism_redirection_substitution.qmd
      chapters: 
        - zero_los_no_procedure_adult.qmd
        - zero_los_no_procedure_child.qmd
        - frail_elderly_intermediate.qmd
        - frail_elderly_high.qmd
        - ambulatory_care_conditions_acute.qmd
        - ambulatory_care_conditions_chronic.qmd
        - ambulatory_care_conditions_vaccine_preventable.qmd
        - readmission_within_28_days.qmd
        - eol_care_2_days.qmd
        - eol_care_3_to_14_days.qmd
        - falls_related_admissions.qmd
        - medicines_related_admissions_explicit.qmd
        - medicines_related_admissions_implicit_anti_diabetics.qmd
        - medicines_related_admissions_implicit_benzodiasepines.qmd
        - medicines_related_admissions_implicit_diurectics.qmd
        - medicines_related_admissions_implicit_nsaids.qmd
    - methods.qmd
    
title-block-banner: "#f9bf07"
title-block-banner-color: "#333739"
format:
  html:
    # embed-resources: true
    smooth-scroll: true
    theme: cosmo
    fontcolor: black
    toc: true
    toc-location: left
    toc-title: Summary
    toc-depth: 3
    grid:
      sidebar-width: 250px
      body-width: 1050px
      margin-width: 0px
      gutter-width: 1.5rem
  # pdf:
  #   documentclass: scrreprt
execute: 
  echo: false
  warning: false
css: styles.css

