# Frail Elderly Admissions

```{r}
library("flextable")

source("R/general.R")
source("R/descriptive_analyses.R")
```

## Descriptive Analysis of Mitigable Activity

### Patient Characteristics

::: panel-tabset

### Age

```{r}
#| label: tbl-perc_frail_age
#| tbl-cap: Mitigable activity for Frail and Elderly Admissions in 22-23 by age.
targets::tar_read(perc_episodes_frail_age) |>
  get_table_perc() 
```

```{r}
#| label: fig-perc_frail_age
#| fig-cap: Mitigable activity for Frail and Elderly Admissions in 22-23 by age.
targets::tar_read(perc_episodes_frail_age) |>
  get_perc_episodes_by_group_plot("age_range")
```

### Ethnicity

```{r}
#| label: tbl-perc_frail_ethnicity
#| tbl-cap: Mitigable activity for Frail and Elderly Admissions in 22-23 by ethnic category.
targets::tar_read(perc_episodes_frail_ethnicity) |>
  get_table_perc() 
```

```{r}
#| label: fig-perc_frail_ethnicity
#| fig-cap: Mitigable activity for Frail and Elderly Admissions in 22-23 by ethnic category.
targets::tar_read(perc_episodes_frail_ethnicity) |>
  get_perc_episodes_by_group_plot("Ethnic_Category")
```

### IMD

```{r}
#| label: tbl-perc_frail_imd
#| tbl-cap: Mitigable activity for Frail and Elderly Admissions in 22-23 by IMD decile.
targets::tar_read(perc_episodes_frail_imd) |>
  get_table_perc() 
```

```{r}
#| label: fig-perc_frail_imd
#| fig-cap: Mitigable activity for Frail and Elderly Admissions in 22-23 by IMD decile.
targets::tar_read(perc_episodes_frail_imd) |>
  dplyr::mutate(imd19_decile = factor(imd19_decile)) |>
  get_perc_episodes_by_group_plot("imd19_decile")
```

### Sex

```{r}
#| label: tbl-perc_frail_sex
#| tbl-cap: Mitigable activity for Frail and Elderly Admissions in 22-23 by sex.
targets::tar_read(perc_episodes_frail_sex) |>
  get_table_perc() 
```

```{r}
#| label: fig-perc_frail_sex
#| fig-cap: Mitigable activity for Frail and Elderly Admissions in 22-23 by sex.
targets::tar_read(perc_episodes_frail_sex) |>
  get_perc_episodes_by_group_plot("sex")
```

:::

### ICB

```{r}
#| label: fig-perc_frail_icb
#| fig-cap: Mitigable activity for Frail and Elderly Admissions in 22-23 by icb.

data <- targets::tar_read(perc_episodes_frail_icb)

icb_pop <- targets::tar_read(icb_population_data) |>
  dplyr::filter(fyear == "2022/23") |>
  dplyr::summarise(pop = sum(icb_population), .by = c(icb24cdh, icb_2024_code))

icb_23_shp <- sf::st_read("https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/Integrated_Care_Boards_April_2023_EN_BGC/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson") |>
  janitor::clean_names()

icb_23_shp |>
  dplyr::left_join(icb_pop, by = c("icb23cd" = "icb_2024_code")) |>
  dplyr::left_join(data, by = c("icb24cdh" = "icb")) |>
  dplyr::mutate(value = janitor::round_half_up(episodes * 100 /
                                                  pop, 2)) |>
  ggplot2::ggplot() +
  ggplot2::geom_sf(ggplot2::aes(fill = value)) +
  ggplot2::theme_void()

# notes
  # value = number episodes at icb * 100 / population at icb
  # using 2023 icb shapefile
```

### LOS

```{r}
#| label: tbl-perc_frail_los
#| tbl-cap: Mitigable activity for Frail and Elderly Admissions in 22-23 by length of stay.
frail_los <- targets::tar_read(perc_episodes_frail_los) |>
  dplyr::mutate(los_range = factor(los_range,
                                   levels = c("0", 
                                              "1",
                                              "2",
                                              "3",
                                              "4-7",
                                              "8-14",
                                              "15-21",
                                              "22+"))) |>
  dplyr::arrange(los_range) 

frail_los |>
  get_table_perc() 
```

```{r}
#| label: fig-perc_frail_los
#| fig-cap: Mitigable activity for Frail and Elderly Admissions in 22-23 by length of stay.
frail_los |>
  get_perc_episodes_by_group_plot("los_range")
```

### Specialty

```{r}
#| label: tbl-perc_frail_mainspecf
#| tbl-cap: Top 10 specialties of mitigable activity for Frail and Elderly Admissions in 22-23.
specialty_key <- targets::tar_read(specialty_key) |>
  dplyr::rename(specialty = main_specialty_title,
                specialty_group = group)

frail_specialties <- targets::tar_read(perc_episodes_frail_mainspef) |>
  dplyr::left_join(specialty_key, by = c("mainspef" = "dd_code"))

frail_specialties |>
  dplyr::arrange(desc(episodes)) |>
  dplyr::slice(1:10) |>
  dplyr::select(specialty, episodes, perc) |>
  get_table_perc() 
```

## Trend Analysis

## Comparative Analysis



