---
title: "local_authority_2x2_charts"
editor: visual
---


```{r packages_and_options}

library("tidyr")
library("dplyr")
library("ggplot2")
library("StrategyUnitTheme")
library("forcats")
library("scales")
library("targets")
library("plotly")
library("patchwork")
library("DT")

source("R/captions.R")
source("R/general.R")
source("R/descriptive_analyses.R")
source("R/comparative_analyses.R")
source("R/Functions for cohort overlap.R")
source("R/Functions for trend analysis.R")
source("R/manipulating_mitigators_and_mechanisms.R")

options(scipen = 999)
options(knitr.duplicate.label = "allow")

```

```{r}
cohort <- "medicines_related_admissions_implicit_nsaids"
roi<-c("Adur", "Lichfield")
```

### Admissions
```{r}

standardised_rates_episodes <- tar_read(la_age_sex_standardised_rates_episodes_over_time) |>
  filter(cohorts == cohort)|>
  mutate(color_group=ifelse(laname23 %in% roi, "1","0"))

plotting_total_activity_vs_percentage_change_LA(standardised_rates_episodes)
```

### Beddays
```{r}

standardised_rates_beddays <- tar_read(la_age_sex_standardised_rates_beddays_over_time) |>
  filter(cohorts == cohort)|>
  mutate(color_group=ifelse(laname23 %in% roi, "1","0"))


plotting_total_activity_vs_percentage_change_LA(standardised_rates_beddays)
```
