```{r}
numbers_over_time <- tar_read(numbers_over_time) |>
  filter(year != "2014/15")

denominator_over_time <- tar_read(denominator_over_time)
icb_population_data <- tar_read(icb_population_data)

number_percentage_over_time <-  data_number_percentage_over_time_icb(
  denominator_over_time,
  numbers_over_time,
  cohort,
  treatment_type)
```

::: panel-tabset
#### Number over time

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("::: panel-tabset")
cat("\n")
cat("##### Admissions")
```

```{r, fig.width=7, fig.height=3}
#| eval: !expr include_admissions
#| label: fig-number_trends_spells_england
#| fig-cap: !expr get_caption_trends(cohort_title, "number", "admissions", "England")
plot_of_number_over_time(number_percentage_over_time, episodes)
```

```{r}
#| output: asis
#| eval: !expr include_beddays
cat("##### Beddays")
```

```{r, fig.width=7, fig.height=3}
#| eval: !expr include_beddays
#| label: fig-number_trends_beddays_england
#| fig-cap: !expr get_caption_trends(cohort_title, "number", "beddays", "England")
plot_of_number_over_time(number_percentage_over_time, beddays)
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat(":::")
```

#### Percentage of `r treatment_type_title` activity

`r cohort_title` as a percentage of `r treatment_type_title` activity.

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("::: panel-tabset")
cat("\n")
cat("##### Admissions")
```

```{r, fig.width=7, fig.height=3}
#| eval: !expr include_admissions
#| label: fig-percent_trends_spells_england
#| fig-cap: !expr get_caption_trends(cohort_title, "perc", "admissions", "England")
plot_of_percentage_over_time(
  number_percentage_over_time |>
    filter(!is.na(percentage_episodes)),
  episodes,
  total_episodes)
```

```{r}
#| output: asis
#| eval: !expr include_beddays
cat("##### Beddays")
```

```{r, fig.width=7, fig.height=3}
#| eval: !expr include_beddays
#| label: fig-percent_trends_beddays_england
#| fig-cap: !expr get_caption_trends(cohort_title, "perc", "beddays", "England")
plot_of_percentage_over_time(
  number_percentage_over_time |>
    filter(!is.na(percentage_beddays)),
  beddays,
  total_beddays)
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat(":::")
```

#### Age and sex standardised rates per 100,000 population

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("::: panel-tabset")
cat("\n")
cat("##### Admissions")
```

```{r, fig.width=7, fig.height=3}
#| eval: !expr include_admissions
#| label: fig-stardardised_trends_spells_england
#| fig-cap: !expr get_caption_trends(cohort_title, "SR", "admissions", "England")
plot_of_standardised_rates_over_time(england_age_sex_standardised_rates_episodes)
```

```{r}
#| output: asis
#| eval: !expr include_beddays
cat("##### Beddays")
```

```{r, fig.width=7, fig.height=3}
#| eval: !expr include_beddays
#| label: fig-stardardised_trends_beddays_england
#| fig-cap: !expr get_caption_trends(cohort_title, "SR", "beddays", "England")
plot_of_standardised_rates_over_time(england_age_sex_standardised_rates_beddays)
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat(":::")
```
:::
