```{r}
overview <- targets::tar_read_raw(glue::glue("overview_{cohort}"))

if(include_admissions) {
  admissions_perc <- overview |>
  dplyr::filter(activity_type == "Admissions") |>
  dplyr::pull(perc)
  
  admissions_statement <- glue::glue("{admissions_perc}% of {treatment_type_title} admissions")
} else {
  admissions_statement <- ""
}

if(include_beddays) {
  beddays_perc <- overview |>
  dplyr::filter(activity_type == "Beddays") |>
  dplyr::pull(perc)
  
  beddays_statement <- glue::glue("{beddays_perc}% of {treatment_type_title} beddays")
} else {
  beddays_statement <- ""
}

statement <- glue::glue("{admissions_statement}{ifelse(include_admissions_and_beddays, ' and ', '')}{beddays_statement}")

if (include_admissions_and_beddays) {
  overview_table <- overview
} else if(include_admissions & !include_admissions_and_beddays) {
  overview_table <- overview |>
    dplyr::filter(activity_type == "Admissions")
} else if(include_beddays & !include_admissions_and_beddays) {
  overview_table <- overview |>
    dplyr::filter(activity_type == "Beddays")
}
```

In 2023/24, `r statement` fall under mitigable activity for the `r cohort_title` cohort.

```{r}
#| label: tbl-overview
#| tbl-cap: !expr get_caption_overview(cohort_title, treatment_type)
overview_table |>
  get_table_perc()
```