To explore how potentially mitigable activity may vary between Local Authority (LA) the table below contains the number, percentage and age and sex standardised rates per 100,000 population of mitigable activity by LA. Columns in the table can be ordered and specific LAs can be searched for.

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("::: panel-tabset")
cat("\n")
cat("##### Admissions")
```

```{r}
activity_type <- "admissions"
summary <- targets::tar_read_raw(glue::glue("summary_{geography}_{activity_type}_{cohort}"))
```

```{r}
#| output: asis
#| eval: !expr include_admissions
knitr::knit_child(
                  input = "child-dir/_child-comparative_local-authority_table.qmd",
                  envir = environment(),
                  quiet = TRUE
                ) |>
                  cat(sep = '\n')
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("##### Beddays")
```

```{r}
activity_type <- "beddays"
summary <- targets::tar_read_raw(glue::glue("summary_{geography}_{activity_type}_{cohort}"))
```

```{r}
#| output: asis
#| eval: !expr include_beddays
knitr::knit_child(
                  input = "child-dir/_child-comparative_local-authority_table.qmd",
                  envir = environment(),
                  quiet = TRUE
                ) |>
                  cat(sep = '\n')
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat(":::")
```