```{r}
caption_admissions <- get_caption_number_of_cohorts(cohort_title, "admissions")
caption_beddays <- get_caption_number_of_cohorts(cohort_title, "beddays")

if(check_if_mechanism(cohort, mitigator_summary_table)) {
  caption_admissions <- glue::glue("{caption_admissions} It includes only admissions for mitigator cohorts within this {cohort_title} group.")
  caption_beddays <- glue::glue("{caption_beddays} It includes only beddays for mitigator cohorts within this {cohort_title} group.")
}
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("::: panel-tabset")
cat("\n")
cat("##### Admissions")
```

```{r, fig.width=4, fig.height=4}
#| eval: !expr include_admissions
#| label: fig-number_of_cohorts_spells
#| fig-cap: !expr caption_admissions

if(check_if_mechanism(cohort, mitigator_summary_table)) {
  plotting_barchart_number_of_cohorts_for_mechanism_group(overlap_numbers, 
                                                          episodes)
} else {
  plotting_barchart_number_of_cohorts(overlap_numbers, episodes)
}
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("##### Beddays")
```

```{r, fig.width=4, fig.height=4}
#| eval: !expr include_beddays
#| label: fig-number_of_cohorts_beddays
#| fig-cap: !expr caption_beddays

if(check_if_mechanism(cohort, mitigator_summary_table)) {
  plotting_barchart_number_of_cohorts_for_mechanism_group(overlap_numbers, 
                                                          beddays)
} else {
  plotting_barchart_number_of_cohorts(overlap_numbers, beddays)
}
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat(":::")
```