```{r}
#| output: false
if(include_admissions) {
  summary_icb_admissions <- targets::tar_read_raw(glue::glue("summary_icb_admissions_{cohort}"))
  
  standardised_rates_admissions <- england_age_sex_standardised_rates_episodes
  
  number_icb_map_admissions <- summary_icb_admissions |>
    get_summary_by_icb_map(icb_23_shp, "total_count")
  
  perc_icb_map_admissions <- summary_icb_admissions |>
    get_summary_by_icb_map(icb_23_shp, "perc")
  
  rate_icb_map_admissions <- summary_icb_admissions |>
    get_summary_by_icb_map(icb_23_shp, "value")
}

if(include_beddays) {
  summary_icb_beddays <- targets::tar_read_raw(glue::glue("summary_icb_beddays_{cohort}"))
  
  standardised_rates_beddays <- england_age_sex_standardised_rates_beddays
  
  number_icb_map_beddays <- summary_icb_beddays |>
    get_summary_by_icb_map(icb_23_shp, "total_count")
  
  perc_icb_map_beddays <- summary_icb_beddays |>
    get_summary_by_icb_map(icb_23_shp, "perc")
  
  rate_icb_map_beddays <- summary_icb_beddays |>
    get_summary_by_icb_map(icb_23_shp, "value")
}
```

::: panel-tabset
#### Number

::: panel-tabset
##### Bars

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("::: panel-tabset")
cat("\n")
cat("##### Admissions")
```

```{r}
#| eval: !expr include_admissions
#| label: fig-number_icb_bar_admissions
#| fig-cap: !expr get_caption_by_geography(cohort_title, "number", "admissions")
england_value <- get_england_value(
  "total_count", 
  data = summary_icb_admissions)

get_summary_by_icb_bar(
  summary_icb_admissions, 
  "total_count", 
  cohort,
  england_value)

rm(england_value)
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("##### Beddays")
```

```{r}
#| eval: !expr include_beddays
#| label: fig-number_icb_bar_beddays
#| fig-cap: !expr get_caption_by_geography(cohort_title, "number", "beddays")
england_value <- get_england_value(
  "total_count", 
  data = summary_icb_beddays)

get_summary_by_icb_bar(
  summary_icb_beddays, 
  "total_count", 
  cohort,
  england_value)

rm(england_value)
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat(":::")
```

##### Map

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("::: panel-tabset")
cat("\n")
cat("##### Admissions")
```

```{r}
#| eval: !expr include_admissions
#| label: fig-number_icb_map_admissions
#| fig-cap: !expr get_caption_by_geography(cohort_title, "number", "admissions")
number_icb_map_admissions
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("##### Beddays")
```

```{r}
#| eval: !expr include_beddays
#| label: fig-number_icb_map_beddays
#| fig-cap: !expr get_caption_by_geography(cohort_title, "number", "beddays")
number_icb_map_beddays
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat(":::")
```
:::

#### Percentage of `r treatment_type_title` activity

::: panel-tabset
##### Bars

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("::: panel-tabset")
cat("\n")
cat("##### Admissions")
```

```{r}
#| eval: !expr include_admissions
#| label: fig-perc_icb_bar_admissions
#| fig-cap: !expr get_caption_by_geography(cohort_title, "perc", "admissions", treatment_type)

england_value <- get_england_value(
  "perc", 
  activity = "admissions",
  treatment = treatment_type,
  data = overview,
  cohort = cohort)

get_summary_by_icb_bar(
  summary_icb_admissions, 
  "perc", 
  cohort,
  england_value)

rm(england_value)
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("##### Beddays")
```

```{r}
#| eval: !expr include_beddays
#| label: fig-perc_icb_bar_beddays
#| fig-cap: !expr get_caption_by_geography(cohort_title, "perc", "beddays", treatment_type)

england_value <- get_england_value(
  "perc", 
  activity = "beddays",
  treatment = treatment_type,
  data = overview,
  cohort = cohort)

get_summary_by_icb_bar(
  summary_icb_beddays, 
  "perc", 
  cohort,
  england_value)

rm(england_value)
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat(":::")
```

##### Map

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("::: panel-tabset")
cat("\n")
cat("##### Admissions")
```

```{r}
#| eval: !expr include_admissions
#| label: fig-perc_icb_map_admissions
#| fig-cap: !expr get_caption_by_geography(cohort_title, "perc", "admissions", treatment_type)
perc_icb_map_admissions
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("##### Beddays")
```

```{r}
#| eval: !expr include_beddays
#| label: fig-perc_icb_map_beddays
#| fig-cap: !expr get_caption_by_geography(cohort_title, "perc", "beddays", treatment_type)
perc_icb_map_beddays
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat(":::")
```
:::

#### Age and sex standardised rates per 100,000 population

::: panel-tabset
##### Bars

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("::: panel-tabset")
cat("\n")
cat("##### Admissions")
```

```{r}
#| eval: !expr include_admissions
#| label: fig-rate_icb_bar_admissions
#| fig-cap: !expr get_caption_by_geography(cohort_title, "SR", "admissions")
england_value <- get_england_value(
  "value",
  data = standardised_rates_admissions,
  cohort = cohort)

get_summary_by_icb_bar(
  summary_icb_admissions, 
  "value", 
  cohort,
  england_value)

rm(england_value)
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("##### Beddays")
```

```{r}
#| eval: !expr include_beddays
#| label: fig-rate_icb_bar_beddays
#| fig-cap: !expr get_caption_by_geography(cohort_title, "SR", "beddays")
england_value <- get_england_value(
  "value",
  data = standardised_rates_beddays,
  cohort = cohort)

get_summary_by_icb_bar(
  summary_icb_beddays, 
  "value", 
  cohort,
  england_value)

rm(england_value)
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat(":::")
```

##### Map

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("::: panel-tabset")
cat("\n")
cat("##### Admissions")
```

```{r}
#| eval: !expr include_admissions
#| label: fig-rate_icb_map_admissions
#| fig-cap: !expr get_caption_by_geography(cohort_title, "SR", "admissions")
rate_icb_map_admissions
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("##### Beddays")
```

```{r}
#| eval: !expr include_beddays
#| label: fig-rate_icb_map_beddays
#| fig-cap: !expr get_caption_by_geography(cohort_title, "SR", "beddays")
rate_icb_map_beddays
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat(":::")
```
:::

#### Table

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("::: panel-tabset")
cat("\n")
cat("##### Admissions")
```

```{r}
#| eval: !expr include_admissions
#| label: tbl-rate_icb_admissions
#| tbl-cap: !expr get_caption_by_geography_table(cohort_title, "admissions", treatment_type, "icb")
get_summary_by_geography_table(
  summary_icb_admissions,
  "admissions", 
  treatment_type)
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("##### Beddays")
```

```{r}
#| eval: !expr include_beddays
#| label: tbl-rate_icb_beddays
#| tbl-cap: !expr get_caption_by_geography_table(cohort_title, "beddays", treatment_type, "icb")
get_summary_by_geography_table(
  summary_icb_beddays,
  "beddays", 
  treatment_type)
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat(":::")
```
:::
