In this section, the number and percentage of mitigable activity for the `r cohort_title` `r cohort_group` are shown by patient characteristics: age, ethnic category, Index of Multiple Deprivation (IMD) decile and sex. Crude rates per 100,000 population are also provided for context.

:::panel-tabset
```{r}
#| output: asis
patient_characteristic <- "age"

knitr::knit_child(input = "child-dir/_child-02_descriptive_patient-characteristics_panel-tabsets.qmd",
                      envir = environment(),
                      quiet = TRUE) |>
      cat(sep = '\n')
```

```{r}
#| output: asis
patient_characteristic <- "ethnicity"

knitr::knit_child(input = "child-dir/_child-02_descriptive_patient-characteristics_panel-tabsets.qmd",
                      envir = environment(),
                      quiet = TRUE) |>
      cat(sep = '\n')
```

```{r}
#| output: asis
patient_characteristic <- "imd"

knitr::knit_child(input = "child-dir/_child-02_descriptive_patient-characteristics_panel-tabsets.qmd",
                      envir = environment(),
                      quiet = TRUE) |>
      cat(sep = '\n')
```

```{r}
#| output: asis
patient_characteristic <- "sex"

knitr::knit_child(input = "child-dir/_child-02_descriptive_patient-characteristics_panel-tabsets.qmd",
                      envir = environment(),
                      quiet = TRUE) |>
      cat(sep = '\n')
```
:::