
As an alternative to Venn diagrams Upset plots are used to show the largest groups (largest single cohorts/overlaps between cohorts).

```{r}
if(cohort_title %in% c("Efficiencies", "Efficiencies & Relocation")) {
most_common_cohort_text<-""
 } else{
most_common_cohort_text<-glue::glue("The 15 most common cohort combinations for the {cohort_title} cohort are shown. All cohort combinations together will add to 100%.")
  }

```

`r most_common_cohort_text`


```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("::: panel-tabset")
cat("\n")
cat("##### Admissions")
```

```{r, fig.width=10, fig.height=6}
#| eval: !expr include_admissions
#| label: upset_plot_frail_elderly_high_episodes
#| fig-cap: !expr get_caption_upset_plots(cohort_title, "admissions")
if(check_if_mechanism(cohort, mitigator_summary_table)) {
  plot_upset_plot_mechanism_group(overlap_numbers, 
                                  mitigator_summary_table, 
                                  episodes)
} else {
  plot_upset_plot(overlap_numbers,  
                  mitigator_summary_table,
                  episodes)
}
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("##### Beddays")
```

```{r, fig.width=10, fig.height=6}
#| eval: !expr include_beddays
#| label: upset_plot_frail_elderly_high_bedday
#| fig-cap: !expr get_caption_upset_plots(cohort_title, "beddays")
if(check_if_mechanism(cohort, mitigator_summary_table)) {
  plot_upset_plot_mechanism_group(overlap_numbers, 
                                  mitigator_summary_table, 
                                  beddays)
} else {
  plot_upset_plot(overlap_numbers,  
                  mitigator_summary_table,
                  beddays)
}
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat(":::")
```