::: panel-tabset
#### Number over time

::: panel-tabset
#### Admissions

```{r, fig.width=7, fig.height=3}
#| label: fig-number_trends_spells_england
#| fig-cap: !expr get_caption_trends(cohort_title, "number", "admissions", "England")
plot_of_number_over_time(number_percentage_over_time, episodes)
```

#### Beddays

```{r, fig.width=7, fig.height=3}
#| label: fig-number_trends_beddays_england
#| fig-cap: !expr get_caption_trends(cohort_title, "number", "beddays", "England")
plot_of_number_over_time(number_percentage_over_time, beddays)
```
:::

#### Percentage of `r treatment_type_title` activity

`r cohort_title` as a percentage of `r treatment_type_title` activity.

::: panel-tabset
#### Admissions

```{r, fig.width=7, fig.height=3}
#| label: fig-percent_trends_spells_england
#| fig-cap: !expr get_caption_trends(cohort_title, "perc", "admissions", "England")
plot_of_percentage_over_time(
  number_percentage_over_time |>
    filter(!is.na(percentage_episodes)),
  episodes,
  total_episodes)
```

#### Beddays

```{r, fig.width=7, fig.height=3}
#| label: fig-percent_trends_beddays_england
#| fig-cap: !expr get_caption_trends(cohort_title, "perc", "beddays", "England")
plot_of_percentage_over_time(
  number_percentage_over_time |>
    filter(!is.na(percentage_beddays)),
  beddays,
  total_beddays)
```
:::

#### Age and sex standardised rates over time

::: panel-tabset
#### Admissions

```{r, fig.width=7, fig.height=3}
#| label: fig-stardardised_trends_spells_england
#| fig-cap: !expr get_caption_trends(cohort_title, "SR", "admissions", "England")
plot_of_standardised_rates_over_time(england_age_sex_standardised_rates_episodes)
```

#### Beddays

```{r, fig.width=7, fig.height=3}
#| label: fig-stardardised_trends_beddays_england
#| fig-cap: !expr get_caption_trends(cohort_title, "SR", "beddays", "England")
plot_of_standardised_rates_over_time(england_age_sex_standardised_rates_beddays)
```
:::
:::
