
Age and sex standardised rates of activity per 100,000 population for local authority areas. 

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("::: panel-tabset")
cat("\n")
cat("##### Admissions")
```

```{r}
#| eval: !expr include_admissions
#| label: table-local_authority_over_time_episodes
#| fig-cap: !expr get_caption_la_trends(cohort_title, "admissions") 
la_age_sex_standardised_rates_episodes_over_time <- tar_read(la_age_sex_standardised_rates_episodes_over_time)

la_episode_table <- generating_la_table(la_age_sex_standardised_rates_episodes_over_time, cohort)

DT::datatable(la_episode_table)
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("##### Beddays")
```

```{r}
#| eval: !expr include_beddays
#| label: table_local_authority_over_time_beddays
#| fig-cap: !expr get_caption_la_trends(cohort_title, "beddays")  
la_age_sex_standardised_rates_beddays_over_time <- tar_read(la_age_sex_standardised_rates_beddays_over_time)

la_beddays_table <- generating_la_table(la_age_sex_standardised_rates_beddays_over_time, cohort)

DT::datatable(la_beddays_table)
```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat(":::")
```
