```{r}
overview <- targets::tar_read_raw(glue::glue("overview_{cohort}"))

if(include_admissions) {
  admissions_number <- overview |>
    dplyr::filter(activity_type == "Admissions") |>
    dplyr::pull(`Mitigable activity`) |>
   janitor::round_half_up(0)|>
    prettyNum(big.mark = ",", scientific = FALSE)

  
  admissions_perc <- overview |>
    dplyr::filter(activity_type == "Admissions") |>
    dplyr::pull(perc)
  
  admissions_statement <- glue::glue(
    "{admissions_perc}% ({admissions_number}) of {treatment_type_title} admissions"
  )
} else {
  admissions_statement <- ""
}

if (include_beddays) {
  beddays_number <- overview |>
    dplyr::filter(activity_type == "Beddays") |>
    dplyr::pull(`Mitigable activity`) |>
      janitor::round_half_up(0)|>
    prettyNum(big.mark = ",", scientific = FALSE)
  
  beddays_perc <- overview |>
    dplyr::filter(activity_type == "Beddays") |>
    dplyr::pull(perc)
  
  beddays_statement <- glue::glue(
    "{beddays_perc}% ({beddays_number}) of {treatment_type_title} beddays"
  )
} else {
  beddays_statement <- ""
}

statement <- glue::glue("{admissions_statement}{ifelse(include_admissions_and_beddays, ' and ', '')}{beddays_statement}")

mechanism_statement <- ifelse(check_if_mechanism(cohort, mitigator_summary_table),
                              "Numbers for each mitigator within this mechanism are presented below.",
                              "")
```

In 2023/24, `r statement` met the criteria for inclusion in the `r cohort_title` mitigator cohort. Beddays are given as the overnight bed count, so those admitted and discharged on the same day will be recorded as having zero beddays. `r mechanism_statement`

```{r}
#| output: asis
#| eval: !expr check_if_mechanism(cohort, mitigator_summary_table)
knitr::knit_child(
  input = "child-dir/_child-overview_mitigator-totals.qmd",
  envir = environment(),
  quiet = TRUE
  ) |>
  cat(sep = '\n')
```