```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("::: panel-tabset")
cat("##### Admissions")
```

```{r, fig.width=10, fig.height=6 }
#| eval: !expr include_admissions
#| label: fig-prop_other_cohorts_frail_spells
#| fig-cap: !expr get_caption_number_of_cohorts(cohort_title, "admissions")

plotting_barchart_summary_of_overlaps(overlap_numbers,
                                      cohort, 
                                      episodes, 
                                      mitigator_summary_table)

```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat("##### Beddays")
```

```{r, fig.width=10, fig.height=7 }
#| eval: !expr include_beddays
#| label: fig-prop_other_cohorts_frail_beddays
#| fig-cap: !expr get_caption_number_of_cohorts(cohort_title, "beddays")

plotting_barchart_summary_of_overlaps(overlap_numbers,
                                      cohort, 
                                      beddays, 
                                      mitigator_summary_table)

```

```{r}
#| output: asis
#| eval: !expr include_admissions_and_beddays
cat(":::")
```